### ISSUE TITLE
Update to 1.8.3

### ISSUE THREAD

**Issue by Kongolan** [CoreNetwork/TradeCraft#46]
Hey there,

can you pull out a build for 1.8.3? 

Changing the packages isn't a problem so far, but it seems like net.minecraft.server.v1_8_R2.BiomeMeta is fully not there anymore. Which leaves a huge gap in the source functionality.

Also line 73 in CostumVillager class isn't working with strings for the map anymore:
CustomRecipe recipe = new CustomRecipe(new ItemStack((Block) Block.REGISTRY.get("bedrock"), 65), new ItemStack((Block) Block.REGISTRY.get("bedrock"), 1));

Those 2 needs a lookup by you, hope you can pull it out pretty soon... I really need it.

- Kongolan

.

**Comment by riddle** [comment]
Update is coming after this weekend, our main developer is busy with exams.
