### ISSUE TITLE
Replacing a vanilla trade

### ISSUE THREAD

**Issue by c0wg0d** [CoreNetwork/TradeCraft#47]
Hi, I have used RebalanceVillagers plugin in the past, but it doesn't support the new villagers in 1.8, so here I am.

All I want to do is replace all the trades for coal to be charcoal instead.  If I add a new trade for charcoal in the config, is that just going to add it to all the possible trades for that villager type, or will that be the only trade, or what?

**Comment by riddle** [comment]
Hi, this plugin can help you replace coal with charcoal for all three professions of the black apron villager, but you’ll have to provide a full tier/trade tree to complete the rest. In that sense, there is no way to cherry pick only 1 trade to edit and leave the rest alone.

I can help you with basics by providing my own config, reduced to only those 3 professions: https://gist.github.com/riddle/d6849b7a6331dc4d87c5

Please notice that enchantments aren’t 100% vanilla. We’ll have a system in the future which can mimic how items villagers sell are enchanted in vanilla game. For now you need to define enchantment possibilities and prices – which can be powerful if you need it and annoying if you don’t, I realize.

Sorry I don’t have a better answer for you for now.
