### ISSUE TITLE
1.9 release bump

### ISSUE THREAD

**Issue by Kongolan** [CoreNetwork/TradeCraft#51]
1.9 is finally out and Spigot has a working build as well.

So just a short bump. Hopefully you can update it soon.

**Comment by riddle** [comment]
Hey, thanks for the update, it’s crazy how fast they do that these days.

I’m gonna be honest with you – there is almost no chance this is going to be updated by us. We closed the last server using this plugin last year before summer so we don’t have a direct need to use this. The update is also not likely to be easy, at least not as easy like for a minor release.

I’m sorry I have to break this news this way and I hope you can find a person or a team who would like to update this and maintain it.

**Comment by Kongolan** [comment]
Actually i already updated it. First i thought i couldn't do it. But once i decompiled the craftbukkit source, it was pretty easy.

**Comment by riddle** [comment]
Awesome. I presume if people wanted to find the updated plugin, they should go to https://github.com/Kongolan/TradeCraft?

**Comment by Kongolan** [comment]
I didn't update my Github for long. But i might do it yes.
